### ISSUE TITLE
Python setup.py script fails in docker img install

### ISSUE THREAD

**Issue by emily-shouppe-stori** [mesibo/python#2]
The `setup.py` script fails when I attempt to install the Python SDK in a docker image.  Relevant lines from Dockerfile are below.

```
FROM python:3.7-buster

RUN apt-get update && \
    apt-get install -y sudo && \
    curl -fsSL https://raw.githubusercontent.com/mesibo/libmesibo/master/install.sh | sudo bash -

RUN git clone https://github.com/mesibo/python.git

RUN cd python && \
    python setup.py install
```

I assume the C/C++ install is successful because I get the following output.
```
Detected Debian Linux ''
installing libmesibo on linux
Installed libmesibo
```

But then I get error output like this after running `python setup.py install`
![Screen Shot 2020-04-03 at 2 46 08 PM](https://user-images.githubusercontent.com/56273800/78394566-dddeff00-75b9-11ea-9fc3-81b6dc356b6d.png)

**Comment by mesibo** [comment]
Thanks for reporting this. The latest libmesibo update broke this which we have fixed now. 

Try again, Send us detail about your docker image, if you still having an issue.

**Comment by emily-shouppe-stori** [comment]
Still having a problem. Dockerfile:
```
FROM python:3.7-buster

RUN apt-get update && \
    apt-get install -y sudo && \
    git clone https://github.com/mesibo/python.git && \
    cd python && \
    python setup.py install
```

I tried installing the C/C++ SDK first as the instructions say here (https://mesibo.com/documentation/install/python/#debianubuntu). But the setup.py script also installs the SDK

**Comment by mesibo** [comment]
Python setup installs C/C++ SDK. It should not harm. There was a typo in the script. We fixed it. Let us know if you still have an issue,

**Comment by emily-shouppe-stori** [comment]
This time it installed but errors were still output.
![Screen Shot 2020-04-06 at 11 15 12 AM](https://user-images.githubusercontent.com/56273800/78574351-e3298d00-77f7-11ea-9af5-e5505cd0a051.png)

**Comment by mesibo** [comment]
Those are warnings. What errors are you getting?

**Comment by emily-shouppe-stori** [comment]
Ah you are correct. I should have read that more closely. Thanks for the quick responses.
