### ISSUE TITLE
api not referenced in send_test_message

### ISSUE THREAD

**Issue by researchase** [mesibo/python#4]
In the example code there is no reference to api object 
def send_text_message(to,message):
        #api is the Mesibo Python API instance. 
        #Make sure the instance is initialised before you call API functions
        p = {}
        p['peer'] = to
        p['expiry'] = 3600
        data = message
        api.send_message(p,api.random(),data) 

I noticed in the javascript example pymesibo object is called api but in python example the object is called pymesibo. I modified the function as below 
def send_text_message(pymesibo,to,message):
        #api is the Mesibo Python API instance. 
        #Make sure the instance is initialised before you call API functions
        p = {}
        p['peer'] = to
        p['expiry'] = 3600
        data = message
        pymesibo.send_message(p,pymesibo.random(),data) 
I sent reference to the object (bad programming I feel) , please can you update the example? 

also please could you show how I can receive and send message at the same time ( I tried threading, works sometimes)

**Comment by mesibo** [comment]
mesibo is a multithreaded library. The start() call will return immediately and hence you need to ensure that your script does not exit, or else use mesibo wait() function to wait indefinitely. 

We have updated README with more examples.
